### ISSUE TITLE
Undeclared dependencies

### ISSUE THREAD

**Issue by eserte** [masakyst/Catalyst-View-MicroTemplate-DataSection#1]
The CPAN Testers Matrix shows a lot of failures: http://matrix.cpantesters.org/?dist=Catalyst-View-MicroTemplate-DataSection%200.02

It seems that these were caused by undeclared dependencies. See:
http://analysis.cpantesters.org/solved?distv=Catalyst-View-MicroTemplate-DataSection-0.02

**Comment by andk** [comment]
http://search.cpan.org/grep?release=Catalyst-View-MicroTemplate-DataSection-0.03;string=TestApp::View::DataSection;n=1;C=0

Still undeclared, the dependency on TestApp::View::DataSection
